import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Menu from "../components/03-organisms/Menu";
import Footer from "../components/03-organisms/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Head>
        <title>Ciotto</title>
        <meta name="description" content="Ciotto" />
        <link rel="stylesheet" href="https://use.typekit.net/xns4hfr.css"></link>
      </Head> */}

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-body-bg text-brown-500`}>
        <Menu />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
